server:
  port: 7072

spring:
  application:
    name: main-records
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db:5432/main_records
    username: services_access
    password: .W}A|#m|k/t.-Pty}RAxi0l+<~e&XNnTM|~tl.#'% V^xiFaQ6e~KGZ}iM#c_]qn9Y3|V|01AHKZ+`yV|odo.S>QErF@`XrV>_E